project_id = "xdjynkgqksdbtbetmrsj"

[functions.send-newsletter-confirmation]
verify_jwt = false

[functions.send-inquiry-reply]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false
